export const ROUTING_PAGE1='ROUTING_PAGE1';
export const ROUTING_PAGE2='ROUTING_PAGE2';

export const GET_SEARCH="GET_SEARCH";
export const REQUEST_SEARCH="REQUEST_SEARCH";

export const GET_RESTAURANTS="GET_RESTAURANTS";
export const REQUEST_RESTAURANTS="REQUEST_RESTAURANTS";

export const GET_VISITED_RESTAURANTS="GET_VISITED_RESTAURANTS";
export const REQUEST_VISITED_RESTAURANTS="REQUEST_VISITED_RESTAURANTS";

export const LOAD='LOAD';

export const PAGE_NUMBER='PAGE_NUMBER';

export const SHOW_ALL_RESTAURANTS = 'SHOW_ALL_RESTAURANTS';
export const SHOW_SEARCHED_RESTAURANTS = 'SHOW_SEARCHED_RESTAURANTS';

export const CHECKED='CHECKED';
export const POSTED='POSTED';