export const ROUTING_PAGE1='ROUTING_PAGE1';
export const ROUTING_PAGE2='ROUTING_PAGE2';

export const GET_SEARCH="GET_SEARCH";
export const REQUEST_SEARCH="REQUEST_SEARCH";

export const GET_RESTAURANTS="GET_RESTAURANTS";
export const REQUEST_RESTAURANTS="REQUEST_RESTAURANTS";

export const GET_VISITED_RESTAURANTS="GET_VISITED_RESTAURANTS";
export const REQUEST_VISITED_RESTAURANTS="REQUEST_VISITED_RESTAURANTS";

export const LOAD='LOAD';